updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
      time: "16:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "19:00"
    labels:
      - ci-cd
