name: Export geotribu mastodon accounts and lists

on:
  schedule:
    - cron: "0 5 * * SUN"  # weekly on sundays
  workflow_dispatch:     # to trigger manually

jobs:

  run:

    runs-on: ubuntu-latest

    steps:

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.12

      - name: Install dependencies
        # TODO: extra for mastodon only
        run: python -m pip install geotribu[all]

      - name: Export geotribu's mastodon lists and accounts
        run: mkdir mastodon && geotribu social mastodon-export -w mastodon/export-mastodon

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "mastodon/export-mastodon"
