name: "💾 Export Geotribu Mastodon accounts and lists"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * SUN" # weekly on sundays
  workflow_dispatch: # to trigger manually

env:
  LANG: "fr_FR.UTF-8"
  LC_ALL: "fr_FR.UTF-8"
  LC_TIME: "fr_FR.UTF-8"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  export:
    name: 📑 Export data
    runs-on: ubuntu-latest
    if: github.repository == 'geotribu/geo-mastodon-comptes-listes'

    steps:
      - name: Get source code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6.1.0
        with:
          cache: "pip"
          cache-dependency-path: "requirements.txt"
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements.txt

      - name: Export geotribu's mastodon lists and accounts
        if: github.actor != 'dependabot[bot]'
        env:
          GEOTRIBU_MASTODON_API_ACCESS_TOKEN: ${{ secrets.GEOTRIBU_MASTODON_API_ACCESS_TOKEN }}
        run: |
          geotribu social mastodon-export -w export/

      - name: Create dummy export for Dependabot
        if: github.actor == 'dependabot[bot]'
        run: |
          mkdir -p export/
          echo "Dependabot test run" > export/README.txt

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: export/

      - name: Save build doc as artifact
        uses: actions/upload-artifact@v5
        with:
          name: export-mastodon
          path: export/
          if-no-files-found: error
          retention-days: 15

  deploy:
    name: 📤 Deploy to GitHub Pages
    needs: export
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: export-mastodon
          path: export/
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: export/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
